

services:
  major:
    container_name: major
    image: error_simulator
    build: .
    ports:
      - "8505:8501"
    command: streamlit run major_error.py --server.port=8501 --server.address=0.0.0.0 

  minor:
    container_name: minor
    image: error_simulator
    build: .
    ports:
      - "8506:8501"
    command: streamlit run minor_error.py --server.port=8501 --server.address=0.0.0.0 